### ISSUE TITLE
Errors in HomeAssistant plugin?

### ISSUE THREAD

**Issue by Lord-Micro** [itsfrosty/homeassistant-control4#2]
Hi,

I've got things running and it does switch my lights, but I'm not able to get the brightness controls working. I do seem to get an error within HomeAssistant related to the control4 python component.

This was in Homeassistant 0.74 and 0.75 and with Control4 2.9.1.

I'm not discounting issues within my my HomeAssistant configuration, but figured I'd ask for help.

light.theatre is as per guide, proxy found using the same code provided.

Thanks in advance

Log Details (ERROR)
Sun Aug 05 2018 18:46:57 GMT+1000 (AEST)

Update for light.theatre fails
Traceback (most recent call last):
  File "/config/custom_components/light/control4.py", line 135, in async_update
    request = yield from websession.get(url)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 387, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 748, in start
    message, payload = await self._protocol.read()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/streams.py", line 533, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 320, in async_device_update
    yield from self.async_update()
  File "/config/custom_components/light/control4.py", line 137, in async_update
    except (asyncio.TimeoutError, aiohttp.errors.ClientError):
AttributeError: module 'aiohttp' has no attribute 'errors'

**Comment by fanlitcn** [comment]
same errors, but it's can control the light by Homeassitant, it's good

**Comment by Lord-Micro** [comment]
is that just an on/off control or with dimming too?

**Comment by fanlitcn** [comment]
> is that just an on/off control or with dimming too?

I  just test the light, its workable, but there hv error infomation on HA, my HA version 0.100.2,  and Climate can not work, HA will issue a lot of error

**Comment by itsfrosty** [comment]
Fixed code to work with 100.2. Please update and let me know if it doesn't work.

Regarding dimming - yes only on/off

**Comment by fanlitcn** [comment]
Many thanks, the Climate can be showed in HA now, but the Temp show 77C, I think it's should be 77F, or 25C,

**Comment by fanlitcn** [comment]
and HA background still ocured errors every interval

Traceback (most recent call last):
  File "/config/custom_components/control4/light.py", line 129, in async_update
    request = yield from websession.get(url)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/control4/light.py", line 130, in async_update
    text = yield from request.text()
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.7/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 268, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_device_update
    await self.async_update()
  File "/config/custom_components/control4/light.py", line 131, in async_update
    except (asyncio.TimeoutError, aiohttp.errors.ClientError):
AttributeError: module 'aiohttp' has no attribute 'errors'

**Comment by itsfrosty** [comment]
F vs C is controlled from your home assistant configuration:
- You can either change it from Configuration->General in your Home Assistant UI
- If it is disabled there, you can check configuration.yaml and change to unit_system: imperial

I am not able to repro the error you are getting. Will keep a lookout and fix it if i am able to repro. I have fixed the "During handling of the above exception, another exception occurred" part of exception above so at least you should see a proper error message

**Comment by allthegoodnamesaretaken** [comment]
I had a similar issue as above, but i traced mine back to the web driver on the control4 controller.  When home assistant polls the controller for a light switch, and requests both the 1000 (State) and 1001 (Brightness) variableID's, the the getVariable function in the 2way driver queries the device for those variables
`function getVariable(proxyID, variableID)
    return C4:GetDeviceVariable(proxyID, variableID)
end`
However, a normal light switch, doesn't have the brightness variable, and as a result, just hangs indefinitely until you hit the timeout and the request it cancelled. I updated that function with the below in driver editor, and updated on the controller, and now it seems to work to test if the variable is valid first, before returning anything. There may be more elegant ways to do this, but this got the job done
`function getVariable(proxyID, variableID)
    valid = false
    for key,value in pairs(C4:GetDeviceVariables(params.proxyID)) do
        if (key == variableID) then
            valid = true
        end
    end
    if valid == true then
        return C4:GetDeviceVariable(proxyID, variableID)
    else
        return
    end
end`

With the getVariable function updated, i also updated the part in the 2way driver, where that function is called, to handle the potential nil value being returned:
`for variableID in string.gmatch(params.variableID, "%d+") do
    msg = msg .. '"' .. variableID .. '":"' .. getVariable(params.proxyID, variableID) .. '",'
end`

to:
`for variableID in string.gmatch(params.variableID, "%d+") do
    variableValue = getVariable(params.proxyID, variableID)
    if variableValue ~= nil then
            msg = msg .. '"' .. variableID .. '":"' .. variableValue .. '",'
    end
end`

The result is the web driver now only returns the variables that are valid for that light

However, All my devices are only showing as on/off switches as you mentioned above. I can confirm the dimmers return the brightness (1001) variable though. I'd appreciate any advice you can offer on that
